steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(HOME)"

- task: CacheBeta@1
  inputs:
    path: C:\Users\tafadnav\tarringtest
    key: \"test4223sds2sdsaa22ddsd332\" | $(Agent.OS) | $(Build.SourcesDirectory)\*.*