steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(HOME)"

- task: CacheBeta@1
  inputs:
    path: C:\__w\1\s\foo.cs
    key: \"test422\" | $(Agent.OS) | $(Build.SourcesDirectory)\foo.cs