steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(HOME)"

- task: CacheBeta@1
  inputs:
    path: $(Build.SourcesDirectory)
    key: \"test4223sds2aa22332\" | $(Agent.OS) | $(Build.SourcesDirectory)\*.*