steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(HOME)"

- task: CacheBeta@1
  inputs:
    path: $(Pipeline.Workspace)\test
    key: \"test42232232\" | $(Agent.OS) | $(Build.SourcesDirectory)\*.*