steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"

- task: CacheBeta@1
  inputs:
    path: C:\Users\tafadnav\Desktop\owendrop\MS.VS.Services.Drop.App\MS.VS.Services.Drop.App
    key: \"test24\" | $(Agent.OS) | $(Build.SourcesDirectory)\foo.cs