steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(Home)"

- task: CacheBeta@1
  inputs:
    path: $(Build.SourcesDirectory)
    key: \"test25\" | $(Agent.OS) | $(Build.SourcesDirectory)\foo.cs