steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(HOME)"

- task: CacheBeta@1
  inputs:
    path: C:\Users\tafadnav\testfolder
    key: \"test4223sds2sdsaa22ddsd332finalnoDcssonsswwt\" | $(Agent.OS) | C:\Users\tafadnav\testfolder\test\s\foo.cs