steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"

- task: CacheBeta@1
  inputs:
    path: $(Home)
    key: \"test25\" | $(Agent.OS) | $(Build.SourcesDirectory)\foo.cs