steps:
#- script: printenv
- script: echo "$(Build.SourcesDirectory)"
- script: echo "$(Pipeline.Workspace)"
- script: echo "$(HOME)"

- task: CacheBeta@1
  inputs:
    path: C:\Users\tafadnav\testfolder
    key: \"blahblash\" | $(Agent.OS) | $(Build.SourcesDirectory)\*