jobs:
- job:
  strategy:
    matrix:
      linux:    
        VM_IMAGE: ubuntu-16.04
      #windows 2017:
      #  VM_IMAGE: vs2017-win2016
      macos 10.13:
        VM_IMAGE: macos-10.13
      macos 10.14:
        VM_IMAGE: macos-10.14
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - template: azure-pipelines-steps.yml

  # Private Pool.
- job: TanmayDev
  pool: tanmaydev
  #container: mcr.microsoft.com/windows/servercore:ltsc2019
  #container: ubuntu:16.04
  steps:
  - template: azure-pipelines-steps.yml

# Linux container pool.
- job: LinuxContainer1604
  pool:
    vmimage: ubuntu-16.04
    container: ubuntu:16.04
  steps:
  - template: azure-pipelines-steps.yml

# Linux container pool.
- job: LinuxContainer1804
  pool:
    vmimage: ubuntu-18.04
    container: ubuntu:18.04
  steps:
  - template: azure-pipelines-steps.yml

# Windows container pool.
#- job: WindowsContainer
#  pool:
#    vmimage: win1803
#    container: mcr.microsoft.com/windows/servercore:1803
#  steps:
#  - template: azure-pipelines-steps.yml